### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by tiagojdias** [fabianbormann/Tensorflow_Segmentation#13]
Hello,

I'm really interested in this work, and i want to test it out.
But during the download i'm not being able to dowload the data.

Is it something from me? I even checked and the url provided is down.

**Comment by fabianbormann** [comment]
Hi @tiagojdias, 
I've also checked the url and .. yes I can confirm it's down right now.
The url points to the original data used in the [caffe implementation](https://github.com/HyeonwooNoh/DeconvNet) .. I had saved the zip files locally but they are quite big :/ ... Don't know if that is only a temporary problem but for now you could maybe download the [VOC2012 dataset](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/) ... the problem is that they are using 2 stages. If your download is finished you are able to run stage 2 ... For stage 1 they use bounding boxes as ground truth instead of the masks, so you need to build something like an OpenCV script that reads the masks, detects the connected component, draws a bounding box around it and save the image.  

Cheers,
Fabian
