### ISSUE TITLE
An error message while running the UnpoolLayerTest.ipynb 

### ISSUE THREAD

**Issue by wenouyang** [fabianbormann/Tensorflow_Segmentation#5]
Hi Fabian,

When experimenting with your code of UnpoolLayerTest.ipynb, I got the following error message. Would you like to take a look at it? I did not change your code.  Thanks.

`Traceback (most recent call last):
  File "UnpoolLayerTest.py", line 56, in <module>
    unpool_1 = unpool_layer2x2(pool_1, unravel_argmax(argmax, tf.to_int64(tf.shape(x))))
  File "UnpoolLayerTest.py", line 17, in unpool_layer2x2
    output = tf.zeros([x_shape[1] * 2, x_shape[2] * 2, x_shape[3]])
  File "/develop/tfw/lib/python3.4/site-packages/tensorflow/python/ops/array_ops.py", line 620, in zeros
    output = constant(0, shape=shape, dtype=dtype, name=name)
  File "/develop/tfw/lib/python3.4/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/develop/tfw/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 363, in make_tensor_proto
    shape = [int(dim) for dim in shape]
  File "/develop/tfw/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 363, in <listcomp>
    shape = [int(dim) for dim in shape]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'
`

**Comment by fabianbormann** [comment]
Hi @wenouyang , what's your tf version? I use currently r0.10 ..

**Comment by wenouyang** [comment]
Hi Fabian, I am using r0.7.  Are there any walkaround if I cannot update version right now, because there are some existing code running on r0.7. Thank you very much.

**Comment by fabianbormann** [comment]
I think it could be very hard to adjust the code and make it running for r0.7 .. your specific error could maybe solved by using the old x.get_shape().as_list() instead of tf.shape(x), but because of many other improvements and changes (see [changelog](https://github.com/tensorflow/tensorflow/blob/r0.10/RELEASE.md)) eg. `Improved support for SparseTensor` in r0.10 you will run in one error after another. So I would recommend to upgrade your existing code to r0.10 or r0.11. That could be easier.
