### ISSUE TITLE
Unpooling gradient problem

### ISSUE THREAD

**Issue by GoldStar89** [fabianbormann/Tensorflow_Segmentation#9]
I try to use a your unpooling implementation. thank you for sharing though.
It works greatly during the forward pass.
but, when back-propagating the gradient through the unpooling layer, i think they don't.
i checked parameters of child(bottom) layer of unpooling layer at training time, they are not changed at all.
do you know why this problem happen?

**Comment by fabianbormann** [comment]
Hi, the implementation was improved by @EmmaBYPeng in a tensorflow discussion about the gradient [it turns out](https://github.com/tensorflow/tensorflow/issues/2169#issuecomment-253568799) that the training works for Emma. Can you share your code or a minimal working example. I will upload another jupyter notebook with a small usage example too.
